/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105436-g98cef1ebbe-20220130"
#endif /* AVUTIL_FFVERSION_H */
